### ISSUE TITLE
Infected Threat is set to -1

### ISSUE THREAD

**Issue by headferd** [Lifars/Dridex-Vaccine#1]
Thank you so much for this script. Really helped out in a massive infection.

Had to to make this change under #### MAIN ####:

#$InfectedThread = -1
[int]$InfectedThread = FindInfectedThread

**Comment by lifarsllc** [comment]
Thank you for reporting this.

Now the detection of infected thread is enabled by default, however, it requires additional time for execution of the script, thus if anybody will want to use this script only for removing Dridex artefacts afterwards (when there is no active Dridex process), this detection of infected thread could be disabled by commenting the affected line.

And you are welcome, we are happy that our vaccine helped you.

**Comment by lifarsllc** [comment]
Resolved
